### ISSUE TITLE
Webpack can't find the module

### ISSUE THREAD

**Issue by aparshin** [tannerjt/classybrew#2]
Webpack can't find `classybrew` module in my project. Looks like the problem is missing definition of an entry point of your module in `package.json`:

```
...
"main": "build/classybrew.min.js",
...
```

By the way, `repository` attribute is incorrect, too.

**Comment by tannerjt** [comment]
@aparshin , thanks for pointing this out.  I've updated the package.json file to hopefully work with webpack.  Instead of pointing to the minified built js file, I specified the main classybrew.js file.  I believe webpack will bundle this for you.  Let me know if the new updates work.

**Comment by aparshin** [comment]
Now everything works well! Thank you for fast response!
